# Generated by Django 3.2.9 on 2021-12-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('picture', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
    ]
