# Generated by Django 3.2.9 on 2021-12-17 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
        ('orders', '0002_auto_20211217_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costumers.costumer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costumers.address'),
        ),
    ]
